# Generated by Django 4.0.6 on 2022-08-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_question_options_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('pub_date',)},
        ),
    ]