# Generated by Django 4.0.6 on 2022-08-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(upload_to='static/'),
        ),
    ]