# Generated by Django 4.0.6 on 2022-08-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_delete_book_alter_profile_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]